[package]
name = "validator"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
dt-xsd = { path = "../xsd" }
clap = { version = "4.5", features = ["derive", "wrap_help"] }
roxmltree = "0.20"
