[package]
name = "test-runner"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
dt-builtins = { path = "../builtins" }
dt-xsd = { path = "../xsd" }
encoding_rs = "0.8.34"
roxmltree = "0.20.0"
