[package]
name = "dt-xsd"
version = "0.1.0"
edition = "2024"
authors = ["Felix Solcher <felix.solcher@gmail.com>"]
description = "Model and parser for XSD schemas"

[dependencies]
roxmltree = "0.20"
thiserror = "2.0"
