pub struct AnyType;
pub struct AnySimpleType;
pub struct AnyAtomicType;
pub struct Error;
pub struct Decimal(pub String);
pub struct DateTime(pub String);
pub struct Duration(pub String);
pub struct Time(pub String);
pub struct Date(pub String);
pub struct GMonth(pub String);
pub struct GMonthDay(pub String);
pub struct GDay(pub String);
pub struct GYear(pub String);
pub struct GYearMonth(pub String);
pub struct HexBinary(pub String);
pub struct Base64Binary(pub String);
pub struct AnyURI(pub String);
pub struct QName(pub String);
pub struct Notation(pub String);
pub struct NormalizedString(pub String);
pub struct Token(pub String);
pub struct Language(pub String);
pub struct NmToken(pub String);
pub struct NmTokens(pub Vec<NmToken>);
pub struct Name(pub String);
pub struct NcName(pub String);
pub struct Id(pub String);
pub struct IdRef(pub String);
pub struct IdRefs(pub Vec<IdRef>);
pub struct Entity(pub String);
pub struct Entities(pub Vec<Entity>);
pub struct Integer(pub String);
pub struct NonPositiveInteger(pub String);
pub struct NegativeInteger(pub String);
pub struct NonNegativeInteger(pub String);
pub struct PositiveInteger(pub String);
pub struct YearMonthDuration(pub String);
pub struct DayTimeDuration(pub String);
pub struct DateTimeStamp(pub String);
